use_frameworks!

platform :ios, '9.0'

install! 'cocoapods', :deterministic_uuids => false

target 'iosApp' do
    pod 'shared', :path => '../shared/'
    
    target 'iosAppTests' do
      inherit! :search_paths
    end
end
